### ISSUE TITLE
Merge describe and list into `get meta`

### ISSUE THREAD

**Issue by YikSanChan** [oom-ai/oomstore#651]
- [x] merge `describe entity` and `list entity` into `get meta entity` (@lianxmfor )
- [x] merge `describe feature` and `list feature` into `get meta feature` (@jinghancc )
- [x] merge `describe group` and `list group` into `get meta group` (@lianxmfor )
