### ISSUE TITLE
Add -o yaml to oomcli command `get meta`

### ISSUE THREAD

**Issue by YikSanChan** [oom-ai/oomstore#694]
This will print the node and all its children instead of a single node.

- [x] Add -o yaml to `get meta entity` (@lianxmfor )
- [x] Add -o yaml to `get meta group` (@lianxmfor )
- [x] Add -o yaml to `get meta feature` (@lianxmfor )
